---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
