---
dist: xenial

language: python

services:
  - docker

node_js:
  - "8"

matrix:
  include:
    - name: "CentOS 7 Tests"
      env:
        - MOLECULE_DISTRO: centos7
        - MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - name: "CentOS 6 Tests"
      env:
        - MOLECULE_DISTRO: centos6
    - name: "Ubuntu 18.04 Tests"
      env:
        - MOLECULE_DISTRO: ubuntu1804
    - name: "Ubuntu 16.04 Tests"
      env:
        - MOLECULE_DISTRO: ubuntu1604
    - name: "Markdown test"
      install:
        # Install markdownlint and markdown-link-check
        - npm install -g markdownlint-cli markdown-link-check > /dev/null
      script:
        # Markdown check
        - |
          echo '"line-length": false' > /tmp/markdownlint_config.json
          find . -name "*.md" -exec markdownlint -c /tmp/markdownlint_config.json {} \;

        # Link Checks
        - |
          echo '{ "ignorePatterns": [ { "pattern": "^(http|https)://localhost" } ] }' > /tmp/config.json
          find . -name "*.md" -exec markdown-link-check --config /tmp/config.json {} \;

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test
