- name: Start NTP service (w32time)
  win_service:
    name: w32time
    state: started

- name: Configure NTP
  win_command: w32tm /config /manualpeerlist:"{{ ntp_servers[0] }}" /reliable:yes /update

- name: Enable Remote Desktop
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
    value: fDenyTSConnections
    data: 0
    datatype: dword

- name: Allow connections from computers running any version of Remote Desktop (less secure)
  win_regedit:
    key: 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
    value: UserAuthentication
    data: 0
    datatype: dword

- name: Allow RDP traffic
  win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- name: Enable Administrator account
  win_user:
    name: Administrator
    account_disabled: no
  when: ansible_distribution | search("Microsoft Windows 10")
